### ISSUE TITLE
Replace Interim GPLv3 Licensing with Proper LGPLv3 License Formatting 

### ISSUE THREAD

**Issue by kircat-concatenation** [Scattercatt/Slippi-stats#3]

**Comment by agung2001** [comment]
hi @kircat-concatenation 👋😄
if that's ok for you, I would like to take this issue.
replacing means change the `LICENSE` content with [LGPLv3 License](https://www.gnu.org/licenses/lgpl-3.0.txt) right?

**Comment by Scattercatt** [comment]
> hi @kircat-concatenation 👋😄 if that's ok for you, I would like to take this issue. replacing means change the `LICENSE` content with [LGPLv3 License](https://www.gnu.org/licenses/lgpl-3.0.txt) right?

Hey agung2001 👋. Feel free to give this a shot. This is my first open repo. Do you have permission to make PRs?

**Comment by agung2001** [comment]
Hi @Scattercatt 
yes I'm able to create a PR it's in [here](https://github.com/Scattercatt/Slippi-stats/pull/8) 
you can review the PR and merge them later 😄👍
